name: Build

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install webpack
        run: npm install --save-dev webpack webpack-cli terser-webpack-plugin ignore-loader

      - name: Prepare build folder
        run: |
          mkdir -p build
          
      - name: Build with Webpack
        run: npx webpack --config webpack.config.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided token
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add build
          git commit -m "Compile latest version" || echo "No changes to commit"
          git push
