name: Build

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install webpack
        run: npm install --save-dev webpack webpack-cli terser-webpack-plugin

      - name: Build with Webpack
        run: npx webpack --config webpack.config.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: fbin
          path: build  # Change this to your output directory
